language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zip unzip
  - echo `whereis zip`
  - echo `whereis unzip`
