language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
before_install:
  - gem update --system
  - gem --version
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zip unzip
  - echo `whereis zip`
  - echo `whereis unzip`
